format = '''
[â•­â”€](bold red) $directoryâ”€â”€ $git_branch$git_state$git_status
[â”‚](bold red)$time $battery $memory_usage
[â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€$character](bold red)
'''

[time]
format = "[$time]($style)"
time_format = "%I:%M %p"
disabled = false

[battery]
format = "[$percentage]($style)"
disabled = false

[[battery.display]]
threshold = 100
style = 'bold red'

[directory]
truncation_length = 3 
truncate_to_repo = false
truncation_symbol = "../"
style = "bold cyan"

[character]
success_symbol = "Î»"
error_symbol = "âŒ"

[python]
symbol = "î˜† "
format = "[${symbol}($virtualenv )]($style)python ($version)"
style = "bold yellow"
detect_extensions = ["py"]
python_binary = ["./venv/bin/python", "python", "python3", "python2"]

[nodejs]
symbol = "ï¢˜ "
format = "via [$symbol $version](bold green)"
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

[git_branch]
format = "[$symbol$branch]($style) "
symbol = "îœ¥ "
style = "bold magenta"

[git_commit]
format = "[($hash$tag)](bold white) "
only_detached = false

[git_status]
style = "bold red"
ahead = "â‡¡${count} "
behind = "â‡£${count} "
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count} "
deleted = "x "

[git_state]
style = "bold yellow"

[memory_usage]
format = "[$symbol[$ram_pct]($style)]"
symbol = "ğŸ§  "
threshold = 10
style = "bold green"

